services:
  laravel.test:
    build:
      context: ../../vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      DB_CONNECTION: mysql
      DB_HOST: '${DB_HOST}'
      DB_PORT: "3306"
      DB_DATABASE: '${DB_DATABASE:-portfolio_db}'
      DB_USERNAME: '${DB_USERNAME:-portfolio_admin}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '../../:/var/www/html'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  migrator:
    image: sail-8.3/app
    restart: "no"
    working_dir: /var/www/html
    volumes:
      - '../../:/var/www/html'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      DB_CONNECTION: mysql
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE:-portfolio_db}'
      DB_USERNAME: '${DB_USERNAME:-portfolio_admin}'
      DB_PASSWORD: '${DB_PASSWORD}'
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      bash -lc 'php artisan migrate --seed --force'

  node:
    image: node:20-bullseye
    working_dir: /var/www/html
    volumes:
      - '../../:/var/www/html'
    command: sh -lc "if [ ! -d node_modules ]; then npm ci; fi; npm run watch"
    networks:
      - sail
    depends_on:
      - laravel.test

  mysql:
    image: 'mariadb:12.1.2'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_DATABASE: '${DB_DATABASE:-portfolio_db}'
      MARIADB_USER: '${DB_USERNAME:-portfolio_admin}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p\"${DB_ROOT_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local
